services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=Password!123
    ports:
      - 1433:1433
  database-seed:
    depends_on: [ database ]
    build:
      dockerfile: DockerfileDatabase
    container_name: database-seed
    volumes:
      - ./database:/database
  wait-for-seeder:
    image: alpine:latest  # A random image that depends on the database-seed service
    depends_on:
      database-seed:
        condition: service_completed_successfully